[package]
name = "f1_light_sync"
version = "0.1.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
f1-game-library-models-25 = "0.2.3"
tokio = { version = "1.48.0", features = ["macros", "net", "rt-multi-thread"] }
